### ISSUE TITLE
Mistakes of master method in notes of ADS

### ISSUE THREAD

**Issue by IsshikiHugh** [Zerokei/Notes#2]
I found some small mistakes(or maybe typo) in the formula 
@ https://notes.zerokei.top/course/ads/divide/#form3
or @ https://github.com/Zerokei/Notes/blob/main/docs/course/ads/divide.md

Where in case 1, `$f(N)=O(N^{\log_b^{a-\epsilon}})$` should be `$f(N)=O(N^{(\log_b{a} )- \epsilon)$`.
In case 3, `$f(N)=\Omega(N^{\log_{b}{a+\epsilon}})$` should be `$f(N)=\Omega(N^{(\log_b{a})+\epsilon})$`.

I mean, the place of the `\epsilon` should out of the log, and an unnecessary `^` is found in case 1.

~~What's more, maybe `\varepsilon` is more beautiful~~.

**Comment by Zerokei** [comment]
fixed, thx!
